// Auto-generated by inertia-mdx-pages. Do not edit.
import React from 'react'
import DocsLayout from '@/layouts/docs-layout';
import { MdxGlobalProvider } from '@/components/docs/mdx-provider'
import MDX, { frontmatter } from '/resources/js/posts/test.mdx'

export default function Page(props) {
  return (
    <DocsLayout slug="test" meta={frontmatter} {...props}>
      <MdxGlobalProvider>
        <MDX />
      </MdxGlobalProvider>
    </DocsLayout>
  )
}
